In [4]:
import numpy as np

In [2]:
b = list(range(10))
b

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
def pythonsum(n):
    a = b = list(range(n))
    c = []
    for i in range(len(a)):
        x = a[1] ** 2
        y = b[i] ** 3
        c.append(x+y)
    return c

c= pythonsum(10)
print(c)

[1, 2, 9, 28, 65, 126, 217, 344, 513, 730]


In [51]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
#a = b = list(range(10))
#range(len(a))


x = y = np.arange(10)
print(x)
np.size(x)

[0 1 2 3 4 5 6 7 8 9]


10

In [7]:
arr = np.array([1,2,3,4,5,6,7,8])
print(arr)

[1 2 3 4 5 6 7 8]


In [8]:
arr = np.append(arr,[9,10])

In [9]:
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [28]:
#multi-dimentional arrays

import numpy as np
multi_list = np.array([[0,1,2,3],[10,11,12,13]]) #array 2D
print (type(multi_list))
bb = multi_list

<class 'numpy.ndarray'>


In [36]:
aa = np.shape(multi_list) #nilai dimensi array 2x4
print(aa)
cc = np.size(multi_list) #panjang arraynya
print(cc)
dd = np.ndim(multi_list) #dimensi berapa
print(dd)

(2, 4)
8
2


In [30]:
print(bb)

[[ 0  1  2  3]
 [10 11 12 13]]


In [31]:
bb[1,3]

13

In [33]:
bb[1,3] = -1
print(bb)

[[ 0  1  2  3]
 [10 11 12 -1]]


In [40]:
## sorting dengan membuat structured array 
dt = np.dtype([('name', 'S10' ), ('height', int), ('age', int)])
#np.array(dtype)
tableArr=(np.zeros(5,),dt)
tableArr


(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 dtype([('name', 'S10'), ('height', '<i8'), ('age', '<i8')]))

In [ ]:
## belajar reshape

In [ ]:
## belajar slicing


In [42]:
print(bb[bb<5])

[ 0  1  2  3 -1]


In [43]:
print(bb[bb>=5])

[10 11 12]


In [ ]:
np.vstack(a,b) # untuk menggabungkan vertikal array a dan b
np.hstack(a,b) # untuk menggabungkan secara horizontal array a dan b
np.hsplit(a,3) # untuk split array jadi 3 bagian

In [45]:
x = [0,1]
y = [2,3]
z = x

print(x)
z[0] = 5
print(x)

[0, 1]
[5, 1]


In [46]:
## fungsi copy

x = [0,1]
y = [2,3]
z = np.copy(x)

print(x)
z[0] = 5
print(x)
print(z)

[0, 1]
[0, 1]
[5 1]


In [50]:
np.ndim(y)

1

In [55]:
data = np.array([[1,2],[3,4],[5,6]])
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [56]:
print(data[0,1])

2


In [57]:
print(data[:])

[[1 2]
 [3 4]
 [5 6]]


In [58]:
print(data[0:2,0])

[1 3]


In [59]:
print(data[:,-1])

[2 4 6]


In [60]:
print(data[0:2,:])

[[1 2]
 [3 4]]


In [61]:
print(data[:,1:])

[[2]
 [4]
 [6]]


In [62]:
arr = np.array([[1,2,3,4],[5,6,7,8],[8,10,11,12],[13,14,15,16]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 8 10 11 12]
 [13 14 15 16]]


In [65]:
print(arr[1::2,::2])

[[ 5  7]
 [13 15]]


In [66]:
## transpose
print(data.transpose())

[[1 3 5]
 [2 4 6]]


In [67]:
np.ndim(arr)

2